# Generated by Django 5.1.5 on 2025-01-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('time', models.TimeField(null=True)),
                ('memo', models.CharField(max_length=500)),
                ('textbook_name', models.CharField(default='教科書', max_length=200)),
                ('peji1', models.IntegerField(default=0)),
                ('peji2', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
