# Generated by Django 5.1.5 on 2025-01-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_study_peji1_alter_study_peji2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='textbook_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
