# Generated by Django 5.1.5 on 2025-01-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_rename_thank_diary_sonohoka'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='tenki',
            new_name='tenki1',
        ),
        migrations.AddField(
            model_name='diary',
            name='tenki2',
            field=models.CharField(default='記録なし', max_length=50),
        ),
    ]
