# Generated by Django 5.1.5 on 2025-01-25 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_rename_tenki_diary_tenki1_diary_tenki2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(default=datetime.date(2025, 1, 25)),
        ),
    ]
