# Generated by Django 5.1.5 on 2025-01-25 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_dd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dd',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
