# Generated by Django 5.1.5 on 2025-01-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_dd_date_alter_diary_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dd',
            old_name='dekigoto',
            new_name='text',
        ),
        migrations.AddField(
            model_name='dd',
            name='title',
            field=models.CharField(default='なし', max_length=300),
        ),
    ]
