# Generated by Django 5.1.5 on 2025-01-25 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_rename_dekigoto_dd_text_dd_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='smoke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
                ('mg', models.IntegerField(default=0)),
                ('honn', models.IntegerField(default=0)),
                ('memo', models.CharField(max_length=500)),
            ],
        ),
    ]
