# Generated by Django 5.1.5 on 2025-01-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_diet_eat'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='play',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
