# Generated by Django 5.1.5 on 2025-01-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_diet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eat',
            name='eat_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
