# Generated by Django 5.1.5 on 2025-01-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_eat_eat_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diet',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diet',
            name='kg',
            field=models.IntegerField(default=0),
        ),
    ]
