# Generated by Django 5.1.5 on 2025-01-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_diet_age_diet_height_diet_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='bmi',
            field=models.CharField(max_length=100),
        ),
    ]
