# Generated by Django 5.1.5 on 2025-01-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_alter_diet_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='eat',
            name='dinner',
            field=models.CharField(default='なし', max_length=1000),
        ),
        migrations.AddField(
            model_name='eat',
            name='lunch',
            field=models.CharField(default='なし', max_length=1000),
        ),
        migrations.AddField(
            model_name='eat',
            name='morning',
            field=models.CharField(default='なし', max_length=1000),
        ),
        migrations.AddField(
            model_name='eat',
            name='sonohoka',
            field=models.CharField(default='なし', max_length=1000),
        ),
        migrations.AlterField(
            model_name='eat',
            name='eat_time',
            field=models.TimeField(default='なし', null=True),
        ),
    ]
