# Generated by Django 5.1.5 on 2025-01-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_eat_dinner_eat_lunch_eat_morning_eat_sonohoka_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eat',
            name='dinner',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='eat',
            name='lunch',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='eat',
            name='morning',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='eat',
            name='sonohoka',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
