# Generated by Django 5.1.5 on 2025-01-29 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_alter_eat_dinner_alter_eat_lunch_alter_eat_morning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eat',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
