# Generated by Django 5.1.5 on 2025-01-29 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_eat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smoke',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
