# Generated by Django 5.1.5 on 2025-01-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_alter_smoke_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smoke',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
