# Generated by Django 5.1.5 on 2025-01-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_alter_smoke_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dd',
            name='title',
            field=models.CharField(default='記録なし', max_length=300),
        ),
        migrations.AlterField(
            model_name='eat',
            name='dinner',
            field=models.CharField(default='記録なし', max_length=1000),
        ),
        migrations.AlterField(
            model_name='eat',
            name='eat_time',
            field=models.TimeField(default='記録なし', null=True),
        ),
        migrations.AlterField(
            model_name='eat',
            name='lunch',
            field=models.CharField(default='記録なし', max_length=1000),
        ),
        migrations.AlterField(
            model_name='eat',
            name='morning',
            field=models.CharField(default='記録なし', max_length=1000),
        ),
        migrations.AlterField(
            model_name='eat',
            name='sonohoka',
            field=models.CharField(default='記録なし', max_length=1000),
        ),
    ]
