# Generated by Django 5.1.5 on 2025-01-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_alter_dd_title_alter_eat_dinner_alter_eat_eat_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dd',
            name='jinbutu',
            field=models.CharField(default='記録なし', max_length=400),
        ),
        migrations.AlterField(
            model_name='dd',
            name='kansou',
            field=models.CharField(default='記録なし', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dd',
            name='text',
            field=models.CharField(default='記録なし', max_length=1000),
        ),
        migrations.AlterField(
            model_name='diary',
            name='hitokoto',
            field=models.CharField(default='記録なし', max_length=100),
        ),
        migrations.AlterField(
            model_name='diary',
            name='sonohoka',
            field=models.CharField(default='記録なし', max_length=300),
        ),
        migrations.AlterField(
            model_name='diary',
            name='text',
            field=models.CharField(default='記録なし', max_length=1000),
        ),
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(default='記録なし', max_length=300),
        ),
        migrations.AlterField(
            model_name='diet',
            name='bmi',
            field=models.CharField(default='計算できませんでした', max_length=100),
        ),
        migrations.AlterField(
            model_name='diet',
            name='play',
            field=models.CharField(default='記録なし', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='time',
            field=models.TimeField(default='00:00', null=True),
        ),
        migrations.AlterField(
            model_name='smoke',
            name='memo',
            field=models.CharField(default='記録なし', max_length=500),
        ),
        migrations.AlterField(
            model_name='smoke',
            name='name',
            field=models.CharField(default='記録なし', max_length=200),
        ),
        migrations.AlterField(
            model_name='study',
            name='memo',
            field=models.CharField(default='記録なし', max_length=500),
        ),
        migrations.AlterField(
            model_name='study',
            name='textbook_name',
            field=models.CharField(default='記録なし', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='time',
            field=models.TimeField(default='00:00', null=True),
        ),
    ]
