# Generated by Django 5.1.5 on 2025-02-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_alter_dd_jinbutu_alter_dd_kansou_alter_dd_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='kyouka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyouka', models.CharField(max_length=100)),
            ],
        ),
    ]
